version: "3.7"

networks:
  mhoney-net1:
    driver: bridge

services:
  app:
    image: nginx:latest
    container_name: mhoney_app
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mhoney-net1
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mhoney_php
    volumes:
      - ./:/var/www/html/
    networks:
      - mhoney-net1
